feat(worker_pool): Shift service creation to the worker pool [Fixes NET-716]
fluencelabs/nox pull request #2026
Opened 2024-01-18 13:14 UTC by gurinderu

## Description
[Provide a brief description of the changes introduced by this pull request and the motivation behind them.]

## Motivation
[Explain why these changes are necessary or beneficial. Discuss any problems or limitations with the current implementation that this pull request addresses.]

## Related Issue(s)
[Cite any related issues or feature requests here, using GitHub issue links.]

## Proposed Changes
[List the specific changes and additions introduced by this pull request.]

## Screenshots (if applicable)
[Add any relevant screenshots or animated GIFs to showcase the changes.]

## Additional Notes
[Provide any additional information or context that may be helpful for the reviewer.]

## Checklist
- [ ] The code follows the project's coding conventions and style guidelines.
- [ ] All tests related to the changes have passed successfully.
- [ ] Documentation has been updated to reflect the changes (if applicable).
- [ ] All new and existing unit tests have passed.
- [ ] I have self-reviewed my code and ensured its quality.
- [ ] I have added/updated necessary comments to aid understanding.

## Reviewer Checklist
- [ ] Code has been reviewed for quality and adherence to [guidelines](https://doc.rust-lang.org/1.0.0/style/README.html).
- [ ] Tests have been reviewed and are sufficient to validate the changes.
- [ ] Documentation has been reviewed and is up to date.
- [ ] Any questions or concerns have been addressed.

2024-01-29 16:27 UTC, kmd-fl reviewed
I haven't finished reading the PR, but so far, I find that I don't like the `PeerScope` structure at all.

2024-01-29 16:27 UTC, kmd-fl commented on particle-services/src/app_services.rs
> +    match peer_scope {
I think thiis function should be simplified just to
```rust
fn resolve_alias(
    services: &Services,
    alias: &String,
    particle_id: &str,
) 
```
and this pattern matching should happen on a level above.

I see this pattern of hiding pattern-matching inside functions in several places in this PR, and I generally think it's wrong and should be avoided, but the whole nox is a mess, so I guess, it's a drop in the ocean

2024-01-30 11:08 UTC, gurinderu commented on particle-builtins/src/builtins.rs
> +        log::info!(
Changed to debug

2024-01-30 11:08 UTC, gurinderu commented on particle-builtins/src/builtins.rs
> +            .public(); //TODO: fix unwrap
Fixed

2024-01-30 11:08 UTC, gurinderu commented on particle-services/src/app_services.rs
> +        entity_id: PeerScope,
Fixed

2024-01-30 11:17 UTC, gurinderu commented on particle-services/src/app_services.rs
> +    pub aliases: RwLock<Vec<ServiceAlias>>,
Write lock where?  for now services stored into 
services: Arc<RwLock<HashMap<ServiceId, Arc<Service>>>>
that means that Service can be accessed from different threads

2024-01-30 11:21 UTC, gurinderu commented on particle-services/src/app_services.rs
> +    match peer_scope {
Fixed

2024-01-30 11:24 UTC, gurinderu commented on crates/system-services/src/deployer.rs
> +            self.host_peer_id,
yep, looks strange, but it is because we have 3 types of different ids, owner_id, host_peer_id and init_peer_id :(

2024-01-30 11:28 UTC, gurinderu commented on aquamarine/src/plumber.rs
> +            let is_host = self.scopes.is_host(particle.particle.init_peer_id);
idk, I have just rewrited the previous version of the code, but you should remember that scope != init_peed_id and here we check that the initiator have permissions for that.  And no, manager_id != worker_id in general

2024-01-31 17:31 UTC, justprosh requested changes

2024-01-31 17:31 UTC, justprosh commented on particle-services/src/app_services.rs
>              //      It actually needs to be able to remove only builtins (services deployed from FS on start),
btw it is obsolete because we don't have builtins from FS now

2024-01-31 17:31 UTC, justprosh commented on particle-services/src/app_services.rs
> +            let mut aliases_service_id_mapping = services.aliases.write();
Seems that deadlock is possible because you take `aliases` and `services` write locks in different order in `remove_service` above

2024-01-31 19:46 UTC, gurinderu commented on crates/workers/src/scope.rs
> +        //TODO: maybe a result ?
it is not only about worker)

2024-01-31 19:47 UTC, gurinderu commented on crates/fs-utils/src/lib.rs
> +const DEFAULT_PARALLELISM: usize = 2;
Fixed

2024-01-31 19:47 UTC, gurinderu commented on crates/nox-tests/tests/spells.rs
> +        log::info!("zalupa {:?}", response);
Fixed

2024-01-31 19:47 UTC, gurinderu commented on crates/nox-tests/tests/spells.rs
> +    enable_logs();
Not needed

2024-01-31 19:47 UTC, gurinderu commented on crates/system-services/src/deployer.rs
> +        let parallelism = available_parallelism().map(|x| x.get()).unwrap_or(2);
Fixed

2024-01-31 19:47 UTC, gurinderu commented on crates/types/Cargo.toml
> +serde = { workspace = true }
Fixed

2024-01-31 19:49 UTC, gurinderu commented on crates/types/src/peer_id.rs
> +pub(crate) mod peer_id_serde {
removed all usages

2024-01-31 19:49 UTC, gurinderu commented on particle-builtins/src/builtins.rs
> +            .public(); //TODO: fix unwrap
Fied

2024-01-31 19:51 UTC, gurinderu commented on particle-services/src/app_services.rs
> +        Err(ServiceError::AliasWrongPeerScope {
yep, not possible anymore, removed

2024-01-31 19:55 UTC, gurinderu commented on particle-services/src/app_services.rs
>              //      It actually needs to be able to remove only builtins (services deployed from FS on start),
Fixed

2024-01-31 19:59 UTC, gurinderu commented on particle-builtins/src/builtins.rs
> +        log::info!(
Fixed

2024-01-31 20:02 UTC, gurinderu commented on particle-services/src/app_services.rs
> +            let mut aliases_service_id_mapping = services.aliases.write();
Fixed

2024-01-31 20:13 UTC, gurinderu commented on crates/workers/src/scope.rs
> +        //TODO: maybe a result ?
Added result

2024-01-31 21:42 UTC, gurinderu commented
> I haven't finished reading the PR, but so far, I find that I don't like the `PeerScope` structure at all.

why?

2024-02-02 11:40 UTC, kmd-fl commented on particle-services/src/app_services.rs
> +        match peer_scope {
Shouldn't something like this work? This would avoid code duplication. I saw such possibilities in other places in this file too.
```rust
       let services = match peer_scope {
            PeerScope::WorkerId(worker_id) => {
                let worker_services = self.worker_services.read();
                worker_services
                    .get(&worker_id)
                    .ok_or(ServiceError::WorkerNotFound { worker_id })?
             },
             PeerScope::Host => &self.root_services,
        };
       let mut aliases = services.aliases.write();
       let mut services = services.services.write();

       aliases.clear();
       services.clear();
```
Or, like Loysha suggested, to just unite these maps

2024-02-02 11:40 UTC, kmd-fl commented on particle-services/src/app_services.rs
> +        };
Maybe we should extend this PeerScope fellow to something like `scope.to_peer_id_or(host_id)` or smth with more conventional naming to reduce the number of patter-matching?   
```suggestion
        let call_parameters_host_id = peer_scope.to_peer_id_or(self.scope.get_host_peer_id().to_string()),
```

This would also improve that ugly interface for `CallParams::local`

2024-02-02 13:10 UTC, justprosh commented on crates/types/src/lib.rs
> +pub const DEFAULT_PARALLELISM: usize = 2;
Why is it here? Maybe move back to workers crate?

2024-02-02 13:11 UTC, justprosh commented on crates/types/src/lib.rs
> +pub const DEFAULT_PARALLELISM: usize = 2;
And leave at least a short doc comment about it. It is default parallelism of what?

2024-02-02 13:14 UTC, justprosh commented on crates/types/Cargo.toml
> +serde_json = { workspace = true }
```suggestion
serde_json = { workspace = true }

```

2024-02-02 13:18 UTC, gurinderu commented on crates/types/src/lib.rs
> +pub const DEFAULT_PARALLELISM: usize = 2;
it is also used in fs-utils, probably it is better to have 2 constants

2024-02-02 13:22 UTC, gurinderu commented on crates/types/src/lib.rs
> +pub const DEFAULT_PARALLELISM: usize = 2;
Fixed

2024-02-02 13:23 UTC, gurinderu commented on crates/types/Cargo.toml
> +serde_json = { workspace = true }
Fixed

2024-02-02 13:38 UTC, justprosh approved these changes

2024-02-02 14:02 UTC, gurinderu commented on particle-services/src/app_services.rs
> +        match peer_scope {
Fixed, now we call get_or_create_services or get_services everywhere if possible

2024-02-02 16:08 UTC, merged